/**
 * Vertical Skin System — Phase 1
 * Token catalog + CSS variable mapping.
 *
 * The CSS_VAR_MAP is the single source of truth for translating typed
 * tokens into the CSS custom properties already consumed by Tailwind
 * (see tailwind.config.ts) and shadcn components. Adding a token here
 * is the only place a new CSS variable name should appear.
 */

import type { ThemeColorTokens } from "./types";

export const COLOR_TOKEN_KEYS: Array<keyof ThemeColorTokens> = [
  "background",
  "foreground",
  "card",
  "cardForeground",
  "popover",
  "popoverForeground",
  "primary",
  "primaryForeground",
  "secondary",
  "secondaryForeground",
  "muted",
  "mutedForeground",
  "accent",
  "accentForeground",
  "destructive",
  "destructiveForeground",
  "border",
  "input",
  "ring",
  "success",
  "successForeground",
  "warning",
  "warningForeground",
  "info",
  "infoForeground",
  "syncing",
  "pendingReview",
  "disconnected",
  "sidebarBackground",
  "sidebarForeground",
  "sidebarPrimary",
  "sidebarPrimaryForeground",
  "sidebarAccent",
  "sidebarAccentForeground",
  "sidebarBorder",
  "sidebarRing",
  "chart1",
  "chart2",
  "chart3",
  "chart4",
  "chart5",
  "nodeStart",
  "nodeQuestion",
  "nodeAction",
  "nodeCondition",
  "nodeEnd",
  "nodeContent",
  "nodeData",
  "nodeLogic",
  "nodeIntegration",
  "nodeCall",
  "nodeAi",
  "nodeFlow",
];

/**
 * Typed token key → CSS custom property name (without the leading `--`).
 * Mirrors src/index.css exactly.
 */
export const CSS_VAR_MAP: Record<keyof ThemeColorTokens, string> = {
  background: "background",
  foreground: "foreground",
  card: "card",
  cardForeground: "card-foreground",
  popover: "popover",
  popoverForeground: "popover-foreground",
  primary: "primary",
  primaryForeground: "primary-foreground",
  secondary: "secondary",
  secondaryForeground: "secondary-foreground",
  muted: "muted",
  mutedForeground: "muted-foreground",
  accent: "accent",
  accentForeground: "accent-foreground",
  destructive: "destructive",
  destructiveForeground: "destructive-foreground",
  border: "border",
  input: "input",
  ring: "ring",
  success: "success",
  successForeground: "success-foreground",
  warning: "warning",
  warningForeground: "warning-foreground",
  info: "info",
  infoForeground: "info-foreground",
  syncing: "syncing",
  pendingReview: "pending-review",
  disconnected: "disconnected",
  sidebarBackground: "sidebar-background",
  sidebarForeground: "sidebar-foreground",
  sidebarPrimary: "sidebar-primary",
  sidebarPrimaryForeground: "sidebar-primary-foreground",
  sidebarAccent: "sidebar-accent",
  sidebarAccentForeground: "sidebar-accent-foreground",
  sidebarBorder: "sidebar-border",
  sidebarRing: "sidebar-ring",
  chart1: "chart-1",
  chart2: "chart-2",
  chart3: "chart-3",
  chart4: "chart-4",
  chart5: "chart-5",
  nodeStart: "node-start",
  nodeQuestion: "node-question",
  nodeAction: "node-action",
  nodeCondition: "node-condition",
  nodeEnd: "node-end",
  nodeContent: "node-content",
  nodeData: "node-data",
  nodeLogic: "node-logic",
  nodeIntegration: "node-integration",
  nodeCall: "node-call",
  nodeAi: "node-ai",
  nodeFlow: "node-flow",
};
