INSERT INTO public.vault_features (slug, name, status, summary, reason_archived, original_routes, frontend_files, restore_notes, archived_at)
VALUES
  ('legacy-user-dashboard', 'Legacy /admin/dashboard page',
   'archived',
   'Original UserDashboardPage that backed /admin/dashboard before Phase 11 collapsed it into /admin (OverviewPage).',
   'Body inlined into OverviewPage; redundant re-export shim deleted.',
   ARRAY['/admin/dashboard'],
   ARRAY['src/pages/admin/UserDashboardPage.tsx'],
   'Restore by reintroducing the file under src/pages/admin/UserDashboardPage.tsx and re-exporting it from OverviewPage.',
   now()),
  ('legacy-scripter-page', 'Legacy /admin/scripter page',
   'archived',
   'ScripterPage — original prose-based script editor superseded by ScriptBuilderPage at /admin/scripts/:scriptId/builder.',
   'Phase C builder consolidation. /admin/scripter now redirects to /admin/scripts.',
   ARRAY['/admin/scripter'],
   ARRAY['src/pages/admin/ScripterPage.tsx'],
   'No surfaced CTAs remain. Restore the file and re-mount the route only if a regression in the canonical builder requires it.',
   now()),
  ('legacy-scriptflow-hub', 'Legacy /admin/scriptflow hub',
   'archived',
   'ScriptFlowHubPage — tabbed wrapper around ScriptRoutingContent. Replaced by canonical guide list at /admin/scripts.',
   'Phase C builder consolidation. /admin/scriptflow now redirects to /admin/scripts.',
   ARRAY['/admin/scriptflow'],
   ARRAY['src/pages/admin/ScriptFlowHubPage.tsx'],
   'Depends on ScriptRoutingPage being restored first (re-exports ScriptRoutingContent).',
   now()),
  ('legacy-tree-editor', 'Legacy React Flow tree editor',
   'archived',
   'TreeEditorPage — original React Flow scripting surface mounted at /admin/tree-editor/:scriptId. Superseded by ScriptBuilderPage.',
   'De-surfaced from primary nav and CTAs in Phase C; deep-link route now redirects to canonical guide list.',
   ARRAY['/admin/tree-editor', '/admin/tree-editor/:scriptId'],
   ARRAY['src/pages/admin/TreeEditorPage.tsx'],
   'Component dependencies under src/components/tree-editor/ are kept (consumed by other surfaces). Restore the page file and re-add the param route to recover deep links.',
   now()),
  ('legacy-script-routing', 'Legacy /admin/script-routing page',
   'archived',
   'ScriptRoutingPage and its embedded ScriptRoutingContent. Campaign↔guide assignment now lives on canonical guide detail.',
   'Phase C convergence. CTAs in ClientOverviewPage rewired to /admin/scripts.',
   ARRAY['/admin/script-routing'],
   ARRAY['src/pages/admin/ScriptRoutingPage.tsx'],
   'Restoring requires also restoring ScriptFlowHubPage if its tab needs to render again.',
   now()),
  ('legacy-five9-campaign-builder', 'Legacy /admin/five9/campaign-builder',
   'archived',
   'CampaignBuilderPage — original drafting surface for Five9 campaigns. Superseded by canonical CampaignIntakePage at /admin/campaigns/new.',
   'Phase B convergence. /admin/five9/campaign-builder + /:draftId now redirect to /admin/campaigns/new. CTAs in Five9OverviewPage and computeCampaignReadiness rewired.',
   ARRAY['/admin/five9/campaign-builder', '/admin/five9/campaign-builder/:draftId'],
   ARRAY['src/pages/admin/CampaignBuilderPage.tsx'],
   'Restore the file and remount the routes if drafting workflow needs to be reintroduced.',
   now()),
  ('legacy-campaigns-overview', 'Legacy /admin/campaigns/overview page',
   'archived',
   'CampaignsOverviewPage — alternate listing surface, never mounted after Phase B. Folded into canonical CampaignsPage at /admin/campaigns.',
   'Already orphaned (no route or import). Vaulted alongside this cleanup pass for completeness.',
   ARRAY['/admin/campaigns/overview'],
   ARRAY['src/pages/admin/CampaignsOverviewPage.tsx'],
   'Restore by adding the route back; canonical /admin/campaigns covers the same scope today.',
   now()),
  ('legacy-campaign-drafts', 'Legacy /admin/campaigns/drafts page',
   'archived',
   'CampaignDraftsPage — superseded by /admin/campaigns?status=draft filter on canonical CampaignsPage.',
   'Already orphaned (no route or import). Vaulted alongside this cleanup pass for completeness.',
   ARRAY['/admin/campaigns/drafts'],
   ARRAY['src/pages/admin/CampaignDraftsPage.tsx'],
   'Restore by adding the route back; canonical filtered list covers the same scope.',
   now())
ON CONFLICT (slug) DO UPDATE SET
  status = EXCLUDED.status,
  summary = EXCLUDED.summary,
  reason_archived = EXCLUDED.reason_archived,
  original_routes = EXCLUDED.original_routes,
  frontend_files = EXCLUDED.frontend_files,
  restore_notes = EXCLUDED.restore_notes,
  archived_at = COALESCE(public.vault_features.archived_at, EXCLUDED.archived_at),
  updated_at = now();